from __future__ import annotations

"""
Generality tests for the closed-system thermodynamic irreversibility framework.

The script is deliberately modular. It tests the same thermodynamic construction in
several microscopically distinct closed quantum systems:

1. 1D interacting hard-core chain (baseline model).
2. 1D interacting Bose-Hubbard chain (different statistics and local Hilbert space).
3. 2D interacting hard-core lattice (different spatial geometry).
4. A broad (V1,V2) scan of the 1D hard-core model (fine-tuning test).
5. A number-conserving Floquet circuit (optional, demonstrates that a static
   Hamiltonian is not required by the theorem).
6. Exact hard-core versus bosonic free-expansion counting in the dilute limit.
7. Time-step refinement of the strong-coupling V1/J=2 boundary.
8. Fixed-time finite-step relative-majorization defect-rate scaling.

All microscopic realizations use one closed system. For a fixed Hamiltonian/unitary
and a fixed fine initial microstate there is one unique microscopic history. The
thermodynamic preparation specifies only a macrostate, so the compatible history
class is generated by the different fine initial microstates consistent with that
same preparation.

All entropy values are reported in units of k_B unless stated otherwise.
"""

import itertools
import math
import pickle
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable

import numpy as np
import scipy.sparse as sp
from scipy.sparse.linalg import expm_multiply
from scipy.special import gammaln

import matplotlib.pyplot as plt
from matplotlib import font_manager


# ============================================================
# Run controls
# ============================================================

BASE_DIR = Path(__file__).resolve().parent if "__file__" in globals() else Path.cwd()
FIG_DIR = BASE_DIR / "generality_figures"
CACHE_DIR = BASE_DIR / "generality_cache"
DATA_DIR = BASE_DIR / "generality_data"

for folder in (FIG_DIR, CACHE_DIR, DATA_DIR):
    folder.mkdir(parents=True, exist_ok=True)

FORCE_RECOMPUTE = False

# Publication mode: cached calculations are reused automatically when available.
RUN_1D_HARDCORE = True
RUN_BOSE_HUBBARD = True
RUN_2D_HARDCORE = True
RUN_PARAMETER_SCAN = True
RUN_CONTROL_FAMILY = True
RUN_FLOQUET = True
RUN_STATISTICS_LIMIT = True
RUN_BOUNDARY_DT_REFINEMENT = True
RUN_LOCAL_DEFECT_RATE = True

# A very small diagnostic mode. Set True only to check the pipeline rapidly.
# The publication calculations use QUICK_TEST = False.
QUICK_TEST = False

# Thermodynamic finite-step resolution used for relative majorization/history defect.
DEFAULT_TAU = 0.10

# Numerical tolerances.
PROB_TOL = 1e-13
MAJ_TOL = 1e-11

# Microscopic energy unit.
J = 1.0


# ============================================================
# Publication plot style: user's preferred Nature/NPG format
# ============================================================

NPG = [
    "#E64B35",
    "#4DBBD5",
    "#00A087",
    "#3C5488",
    "#F39B7F",
    "#8491B4",
    "#91D1C2",
    "#DC0000",
    "#7E6148",
]

RED = NPG[0]
BLUE = NPG[1]
GREEN = NPG[2]
NAVY = NPG[3]
SALMON = NPG[4]
PURPLE = NPG[5]
MINT = NPG[6]
DARK_RED = NPG[7]
BROWN = NPG[8]
GRAY = "#7A7A7A"
LIGHT_GRAY = "#D9D9D9"
BLACK = "black"

available_fonts = {f.name for f in font_manager.fontManager.ttflist}
MAIN_FONT = "Times New Roman" if "Times New Roman" in available_fonts else "DejaVu Serif"
Fontsize = 14
plt.rcParams.update(
    {
        "font.family": MAIN_FONT,
        "font.size": Fontsize,
        "axes.labelsize": Fontsize,
        "xtick.labelsize": Fontsize,
        "ytick.labelsize": Fontsize,
        "legend.fontsize": Fontsize,
        "axes.linewidth": 1.0,
        "lines.linewidth": 1.5,
        "lines.markersize": 4.0,
        "xtick.direction": "in",
        "ytick.direction": "in",
        "xtick.top": True,
        "ytick.right": True,
        "xtick.major.width": 0.9,
        "ytick.major.width": 0.9,
        "xtick.major.size": 4.0,
        "ytick.major.size": 4.0,
        "xtick.minor.size": 2.0,
        "ytick.minor.size": 2.0,
        "legend.frameon": False,
        "mathtext.fontset": "stix",
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "figure.max_open_warning": 0,
    }
)


def finish_axes(ax):
    ax.minorticks_on()


def panel_label(ax, label, x=0.03, y=0.95):
    ax.text(
        x,
        y,
        label,
        transform=ax.transAxes,
        va="top",
        ha="left",
        color=BLACK,
    )


def savefig(fig, filename: str, h_pad=None, w_pad=None):
    path = FIG_DIR / filename
    fig.tight_layout(pad=0.35, h_pad=h_pad, w_pad=w_pad)
    fig.savefig(
        path,
        bbox_inches="tight",
        pad_inches=0.01,
        transparent=False,
    )
    print(f"Saved: {path}")
    plt.show()


# ============================================================
# Generic numerical utilities
# ============================================================


def cached(name: str, builder: Callable[[], dict]):
    path = CACHE_DIR / f"{name}.pkl"
    if path.exists() and not FORCE_RECOMPUTE:
        print(f"Loading cache: {path}")
        with path.open("rb") as f:
            return pickle.load(f)

    print(f"Computing: {name}")
    data = builder()
    with path.open("wb") as f:
        pickle.dump(data, f, protocol=pickle.HIGHEST_PROTOCOL)
    print(f"Cached: {path}")
    return data


def log_binom(n: int, k: int) -> float:
    if k < 0 or k > n:
        return -np.inf
    return float(gammaln(n + 1) - gammaln(k + 1) - gammaln(n - k + 1))


def log_multichoose(L: int, Q: int) -> float:
    """log number of weak compositions of Q bosons among L sites."""
    if L <= 0 or Q < 0:
        return -np.inf
    return log_binom(L + Q - 1, Q)


def safe_normalize(p: np.ndarray) -> np.ndarray:
    p = np.asarray(p, dtype=float).copy()
    p[np.abs(p) < PROB_TOL] = 0.0
    p[p < 0.0] = 0.0
    s = p.sum()
    if s <= 0.0:
        raise ValueError("Probability vector has non-positive normalization.")
    return p / s


def coarse_entropy(p: np.ndarray, omega: np.ndarray) -> float:
    """S_R/k_B = -sum_R p_R log(p_R/Omega_R)."""
    p = safe_normalize(p)
    omega = np.asarray(omega, dtype=float)
    mask = p > 0.0
    return float(-np.sum(p[mask] * np.log(p[mask] / omega[mask])))


def relative_entropy(p: np.ndarray, pi: np.ndarray) -> float:
    p = safe_normalize(p)
    pi = safe_normalize(pi)
    mask = p > 0.0
    return float(np.sum(p[mask] * np.log(p[mask] / pi[mask])))


def generalized_lorenz_points(p: np.ndarray, pi: np.ndarray):
    """Return generalized Lorenz curve breakpoints (x,y)."""
    p = safe_normalize(p)
    pi = safe_normalize(pi)
    if np.any(pi <= 0.0):
        raise ValueError("pi must have full support on the included macrostates.")

    order = np.argsort(-(p / pi), kind="mergesort")
    xs = np.concatenate([[0.0], np.cumsum(pi[order])])
    ys = np.concatenate([[0.0], np.cumsum(p[order])])
    xs[-1] = 1.0
    ys[-1] = 1.0
    return xs, ys


def lorenz_value(xs: np.ndarray, ys: np.ndarray, x: np.ndarray) -> np.ndarray:
    return np.interp(x, xs, ys)


def majorization_defect(p: np.ndarray, q: np.ndarray, pi: np.ndarray) -> float:
    """
    V_pi(p -> q) = sup_x [L_q^pi(x)-L_p^pi(x)]_+.

    Since both curves are piecewise linear, it is sufficient to evaluate the
    difference at the union of their breakpoints.
    """
    xp, yp = generalized_lorenz_points(p, pi)
    xq, yq = generalized_lorenz_points(q, pi)
    x = np.unique(np.concatenate([xp, xq]))
    diff = lorenz_value(xq, yq, x) - lorenz_value(xp, yp, x)
    return float(max(0.0, np.max(diff)))


def lorenz_margin(p: np.ndarray, q: np.ndarray, pi: np.ndarray) -> float:
    """Minimum L_p-L_q over all generalized-Lorenz breakpoints."""
    xp, yp = generalized_lorenz_points(p, pi)
    xq, yq = generalized_lorenz_points(q, pi)
    x = np.unique(np.concatenate([xp, xq]))
    diff = lorenz_value(xp, yp, x) - lorenz_value(xq, yq, x)
    return float(np.min(diff))


def group_sum(values: np.ndarray, macro_id: np.ndarray, n_macro: int) -> np.ndarray:
    return np.bincount(macro_id, weights=np.asarray(values, dtype=float), minlength=n_macro)


def first_crossing(y: np.ndarray, level: float, start: int = 0):
    idx = np.where(np.asarray(y)[start:] >= level)[0]
    if len(idx) == 0:
        return None
    return int(start + idx[0])


def primary_window_indices(sigma: np.ndarray):
    i10 = first_crossing(sigma, 0.10)
    if i10 is None:
        return None, None
    i90 = first_crossing(sigma, 0.90, start=i10)
    return i10, i90


def entropy_return_depth(sigma: np.ndarray, i90: int | None) -> float:
    if i90 is None or i90 >= len(sigma) - 1:
        return np.nan
    running_max = -np.inf
    max_drop = 0.0
    for value in sigma[i90:]:
        running_max = max(running_max, value)
        max_drop = max(max_drop, running_max - value)
    return float(max_drop)


@dataclass
class MacroData:
    labels: list[tuple]
    macro_id: np.ndarray
    omega: np.ndarray
    pi: np.ndarray


@dataclass
class Trajectory:
    times: np.ndarray
    p: np.ndarray
    entropy: np.ndarray
    sigma: np.ndarray
    rate: np.ndarray | None
    vpi: np.ndarray
    margin: np.ndarray
    epsilon_hist: np.ndarray | None
    ds_mix: np.ndarray | None
    ds_corr: np.ndarray | None
    i10: int | None
    i90: int | None
    metadata: dict


# ============================================================
# Generic class-level trajectory calculation
# ============================================================


def basis_columns(dim: int, indices: Iterable[int]) -> np.ndarray:
    idx = np.asarray(list(indices), dtype=int)
    psi0 = np.zeros((dim, len(idx)), dtype=np.complex128)
    psi0[idx, np.arange(len(idx))] = 1.0
    return psi0


def macro_probabilities_from_columns(psi: np.ndarray, macro: MacroData) -> np.ndarray:
    # psi shape = (dim, n_columns); equal-weight thermodynamic class.
    site_prob = np.mean(np.abs(psi) ** 2, axis=1)
    return safe_normalize(group_sum(site_prob, macro.macro_id, len(macro.omega)))


def macro_rate_from_columns(
    psi: np.ndarray,
    H: sp.spmatrix,
    macro: MacroData,
) -> np.ndarray:
    dpsi = -1j * (H @ psi)
    dsite = np.mean(2.0 * np.real(np.conj(psi) * dpsi), axis=1)
    return group_sum(dsite, macro.macro_id, len(macro.omega))


def entropy_rate_from_dp(p: np.ndarray, dp: np.ndarray, omega: np.ndarray) -> float:
    p = safe_normalize(p)
    mask = p > 1e-15
    # The normalization term vanishes because sum dp = 0.
    return float(-np.sum(dp[mask] * np.log(p[mask] / omega[mask])))


def build_coarse_K_from_step(
    dim: int,
    macro: MacroData,
    step_action: Callable[[np.ndarray], np.ndarray],
) -> np.ndarray:
    """
    Construct the exact macro-uniform K^(U) for one finite unitary step.

    K_RR' is obtained by uniformly averaging over all microscopic basis states
    belonging to initial macrospace R'. This is practical for the representative
    systems used here (dimensions O(10^2)-O(10^3)).
    """
    eye = np.eye(dim, dtype=np.complex128)
    Ucols = step_action(eye)
    n_macro = len(macro.omega)

    # T[R, j] = probability to end in macro R from microscopic basis state j.
    T = np.zeros((n_macro, dim), dtype=float)
    abs2 = np.abs(Ucols) ** 2
    for j in range(dim):
        T[:, j] = group_sum(abs2[:, j], macro.macro_id, n_macro)

    K = np.zeros((n_macro, n_macro), dtype=float)
    for rp in range(n_macro):
        cols = np.where(macro.macro_id == rp)[0]
        if len(cols) != int(round(macro.omega[rp])):
            raise RuntimeError("Macrospace dimension does not match basis grouping.")
        K[:, rp] = np.mean(T[:, cols], axis=1)

    # Small numerical cleanup.
    K[np.abs(K) < 1e-15] = 0.0
    return K


def verify_K(K: np.ndarray, pi: np.ndarray):
    stoch_err = float(np.max(np.abs(np.sum(K, axis=0) - 1.0)))
    pi_err = float(np.max(np.abs(K @ pi - pi)))
    min_entry = float(np.min(K))
    return stoch_err, pi_err, min_entry


def analyze_time_independent_class(
    H: sp.spmatrix,
    macro: MacroData,
    initial_indices: list[int],
    times: np.ndarray,
    tau: float,
    compute_history_defect: bool = True,
    metadata: dict | None = None,
) -> Trajectory:
    dim = H.shape[0]
    psi0 = basis_columns(dim, initial_indices)

    # expm_multiply returns shape (nt, dim, n_initial) for matrix B.
    states = expm_multiply(
        -1j * H,
        psi0,
        start=float(times[0]),
        stop=float(times[-1]),
        num=len(times),
        endpoint=True,
    )

    nt = len(times)
    n_macro = len(macro.omega)
    p = np.zeros((nt, n_macro), dtype=float)
    entropy = np.zeros(nt, dtype=float)
    rate = np.zeros(nt, dtype=float)

    for it in range(nt):
        p[it] = macro_probabilities_from_columns(states[it], macro)
        entropy[it] = coarse_entropy(p[it], macro.omega)
        dp = macro_rate_from_columns(states[it], H, macro)
        rate[it] = entropy_rate_from_dp(p[it], dp, macro.omega)

    S0 = entropy[0]
    Smax = math.log(float(np.sum(macro.omega)))
    denom = Smax - S0
    sigma = (entropy - S0) / denom if denom > 0 else np.zeros_like(entropy)

    vpi = np.full(nt - 1, np.nan)
    margin = np.full(nt - 1, np.nan)
    for it in range(nt - 1):
        vpi[it] = majorization_defect(p[it], p[it + 1], macro.pi)
        margin[it] = lorenz_margin(p[it], p[it + 1], macro.pi)

    epsilon_hist = None
    ds_mix = None
    ds_corr = None

    dt = float(times[1] - times[0])
    if compute_history_defect:
        if abs(dt - tau) > 1e-10:
            raise ValueError("For history-defect calculation, grid spacing must equal tau.")

        step_action = lambda X: expm_multiply(-1j * H * tau, X)
        K = build_coarse_K_from_step(dim, macro, step_action)
        stoch_err, pi_err, min_entry = verify_K(K, macro.pi)
        print(
            "K checks:",
            f"stochasticity={stoch_err:.3e},",
            f"pi-preservation={pi_err:.3e},",
            f"min entry={min_entry:.3e}",
        )

        epsilon_hist = np.zeros(nt - 1, dtype=float)
        ds_mix = np.zeros(nt - 1, dtype=float)
        ds_corr = np.zeros(nt - 1, dtype=float)

        for it in range(nt - 1):
            q0 = safe_normalize(K @ p[it])
            q = p[it + 1]
            r = q - q0
            epsilon_hist[it] = 0.5 * np.sum(np.abs(r))
            ds_mix[it] = coarse_entropy(q0, macro.omega) - coarse_entropy(p[it], macro.omega)
            ds_corr[it] = coarse_entropy(q, macro.omega) - coarse_entropy(q0, macro.omega)

            # Exact numerical bound check.
            if vpi[it] - epsilon_hist[it] > 5e-10:
                raise RuntimeError("Numerical violation of V_pi <= epsilon_hist.")

    i10, i90 = primary_window_indices(sigma)

    md = dict(metadata or {})
    md.update(
        {
            "dim": dim,
            "initial_class_dim": len(initial_indices),
            "S0": S0,
            "Smax": Smax,
            "return_depth": entropy_return_depth(sigma, i90),
        }
    )

    return Trajectory(
        times=times,
        p=p,
        entropy=entropy,
        sigma=sigma,
        rate=rate,
        vpi=vpi,
        margin=margin,
        epsilon_hist=epsilon_hist,
        ds_mix=ds_mix,
        ds_corr=ds_corr,
        i10=i10,
        i90=i90,
        metadata=md,
    )


# ============================================================
# 1D hard-core chain
# ============================================================


def fixed_q_hardcore_basis(N: int, Q: int):
    basis = []
    for occupied in itertools.combinations(range(N), Q):
        b = 0
        for j in occupied:
            b |= 1 << j
        basis.append(b)
    return basis, {b: i for i, b in enumerate(basis)}


def build_hardcore_1d_hamiltonian(
    N: int,
    Q: int,
    V1: float,
    V2: float,
    hopping: float = J,
):
    basis, index = fixed_q_hardcore_basis(N, Q)
    rows, cols, vals = [], [], []

    for col, b in enumerate(basis):
        diag = 0.0
        for j in range(N - 1):
            diag += V1 * ((b >> j) & 1) * ((b >> (j + 1)) & 1)
        for j in range(N - 2):
            diag += V2 * ((b >> j) & 1) * ((b >> (j + 2)) & 1)
        rows.append(col)
        cols.append(col)
        vals.append(diag)

        for j in range(N - 1):
            nj = (b >> j) & 1
            nk = (b >> (j + 1)) & 1
            if nj == nk:
                continue
            b2 = b ^ (1 << j) ^ (1 << (j + 1))
            rows.append(index[b2])
            cols.append(col)
            vals.append(-hopping)

    H = sp.csr_matrix(
        (vals, (rows, cols)), shape=(len(basis), len(basis)), dtype=np.complex128
    )
    return H, basis, index


def hard_core_1d_macro_data(basis: list[int], N: int, Q: int, Kcells: int = 4):
    if N % Kcells != 0:
        raise ValueError("N must be divisible by Kcells.")
    ell = N // Kcells

    labels = []

    def rec(prefix, remaining, cells_left):
        if cells_left == 1:
            if 0 <= remaining <= ell:
                labels.append(tuple(prefix + [remaining]))
            return
        for n in range(min(ell, remaining) + 1):
            rec(prefix + [n], remaining - n, cells_left - 1)

    rec([], Q, Kcells)
    labels = sorted(labels)
    label_to_id = {r: i for i, r in enumerate(labels)}

    macro_id = np.empty(len(basis), dtype=int)
    for ib, b in enumerate(basis):
        counts = []
        for a in range(Kcells):
            lo = a * ell
            hi = (a + 1) * ell
            count = sum((b >> j) & 1 for j in range(lo, hi))
            counts.append(count)
        macro_id[ib] = label_to_id[tuple(counts)]

    omega = np.array(
        [np.prod([math.comb(ell, n) for n in r]) for r in labels], dtype=float
    )
    pi = omega / np.sum(omega)

    # Exact consistency with the computational basis.
    group_counts = np.bincount(macro_id, minlength=len(labels))
    if not np.array_equal(group_counts, omega.astype(int)):
        raise RuntimeError("Hard-core macro multiplicity mismatch.")

    return MacroData(labels=labels, macro_id=macro_id, omega=omega, pi=pi)


def hard_core_left_half_initial_indices(basis: list[int], N: int, Q: int):
    Li = N // 2
    mask_right = sum(1 << j for j in range(Li, N))
    indices = [i for i, b in enumerate(basis) if (b & mask_right) == 0]
    expected = math.comb(Li, Q)
    if len(indices) != expected:
        raise RuntimeError("Initial hard-core class dimension mismatch.")
    return indices


def build_hardcore_1d_control_hamiltonian(N: int, Q: int, mode: str):
    """Uniform free hopping or matched-topology engineered mirror-return chain."""
    basis, index = fixed_q_hardcore_basis(N, Q)
    rows, cols, vals = [], [], []

    for col, b in enumerate(basis):
        rows.append(col)
        cols.append(col)
        vals.append(0.0)

        for j0 in range(N - 1):
            nj = (b >> j0) & 1
            nk = (b >> (j0 + 1)) & 1
            if nj == nk:
                continue

            if mode == "free":
                hop = -J
            elif mode == "engineered":
                j = j0 + 1
                hop = -(2.0 * J / N) * math.sqrt(j * (N - j))
            else:
                raise ValueError("mode must be 'free' or 'engineered'.")

            b2 = b ^ (1 << j0) ^ (1 << (j0 + 1))
            rows.append(index[b2])
            cols.append(col)
            vals.append(hop)

    H = sp.csr_matrix(
        (vals, (rows, cols)), shape=(len(basis), len(basis)), dtype=np.complex128
    )
    return H, basis, index


# ============================================================
# 1D Bose-Hubbard chain
# ============================================================


def weak_compositions(total: int, parts: int):
    if parts == 1:
        yield (total,)
        return
    for n in range(total + 1):
        for rest in weak_compositions(total - n, parts - 1):
            yield (n,) + rest


def fixed_q_boson_basis(L: int, Q: int):
    basis = list(weak_compositions(Q, L))
    return basis, {state: i for i, state in enumerate(basis)}


def build_bose_hubbard_hamiltonian(
    L: int,
    Q: int,
    U: float,
    hopping: float = J,
):
    basis, index = fixed_q_boson_basis(L, Q)
    rows, cols, vals = [], [], []

    for col, state in enumerate(basis):
        n = np.asarray(state, dtype=int)
        diag = 0.5 * U * float(np.sum(n * (n - 1)))
        rows.append(col)
        cols.append(col)
        vals.append(diag)

        for j in range(L - 1):
            # Move one boson from j+1 -> j.
            if n[j + 1] > 0:
                new = list(state)
                amp = -hopping * math.sqrt((n[j] + 1) * n[j + 1])
                new[j] += 1
                new[j + 1] -= 1
                rows.append(index[tuple(new)])
                cols.append(col)
                vals.append(amp)

            # Move one boson from j -> j+1.
            if n[j] > 0:
                new = list(state)
                amp = -hopping * math.sqrt((n[j + 1] + 1) * n[j])
                new[j] -= 1
                new[j + 1] += 1
                rows.append(index[tuple(new)])
                cols.append(col)
                vals.append(amp)

    H = sp.csr_matrix(
        (vals, (rows, cols)), shape=(len(basis), len(basis)), dtype=np.complex128
    )
    return H, basis, index


def boson_1d_macro_data(basis: list[tuple], L: int, Q: int, Kcells: int = 4):
    if L % Kcells != 0:
        raise ValueError("L must be divisible by Kcells.")
    ell = L // Kcells

    labels = sorted(set(weak_compositions(Q, Kcells)))
    label_to_id = {r: i for i, r in enumerate(labels)}

    macro_id = np.empty(len(basis), dtype=int)
    for ib, state in enumerate(basis):
        counts = []
        for a in range(Kcells):
            lo = a * ell
            hi = (a + 1) * ell
            counts.append(int(sum(state[lo:hi])))
        macro_id[ib] = label_to_id[tuple(counts)]

    omega = np.array(
        [
            np.prod([math.comb(ell + n - 1, n) for n in r])
            for r in labels
        ],
        dtype=float,
    )
    pi = omega / np.sum(omega)

    group_counts = np.bincount(macro_id, minlength=len(labels))
    if not np.array_equal(group_counts, omega.astype(int)):
        raise RuntimeError("Bosonic macro multiplicity mismatch.")

    return MacroData(labels=labels, macro_id=macro_id, omega=omega, pi=pi)


def boson_left_half_initial_indices(basis: list[tuple], L: int, Q: int):
    Li = L // 2
    indices = [i for i, state in enumerate(basis) if sum(state[Li:]) == 0]
    expected = math.comb(Li + Q - 1, Q)
    if len(indices) != expected:
        raise RuntimeError("Initial bosonic class dimension mismatch.")
    return indices


# ============================================================
# 2D hard-core lattice
# ============================================================


def square_lattice_edges(Lx: int, Ly: int):
    edges = []
    for y in range(Ly):
        for x in range(Lx):
            i = y * Lx + x
            if x + 1 < Lx:
                edges.append((i, y * Lx + (x + 1)))
            if y + 1 < Ly:
                edges.append((i, (y + 1) * Lx + x))
    return edges


def build_hardcore_2d_hamiltonian(
    Lx: int,
    Ly: int,
    Q: int,
    V: float,
    hopping: float = J,
):
    N = Lx * Ly
    basis, index = fixed_q_hardcore_basis(N, Q)
    edges = square_lattice_edges(Lx, Ly)
    rows, cols, vals = [], [], []

    for col, b in enumerate(basis):
        diag = 0.0
        for i, j in edges:
            diag += V * ((b >> i) & 1) * ((b >> j) & 1)
        rows.append(col)
        cols.append(col)
        vals.append(diag)

        for i, j in edges:
            ni = (b >> i) & 1
            nj = (b >> j) & 1
            if ni == nj:
                continue
            b2 = b ^ (1 << i) ^ (1 << j)
            rows.append(index[b2])
            cols.append(col)
            vals.append(-hopping)

    H = sp.csr_matrix(
        (vals, (rows, cols)), shape=(len(basis), len(basis)), dtype=np.complex128
    )
    return H, basis, index, edges


def quadrant_of_site(x: int, y: int, Lx: int, Ly: int):
    # Ordering keeps the two left quadrants first:
    # 0 = lower-left, 1 = upper-left, 2 = lower-right, 3 = upper-right.
    left = x < Lx // 2
    lower = y < Ly // 2
    if left and lower:
        return 0
    if left and not lower:
        return 1
    if not left and lower:
        return 2
    return 3


def hard_core_2d_macro_data(basis: list[int], Lx: int, Ly: int, Q: int):
    if Lx % 2 or Ly % 2:
        raise ValueError("Use even Lx and Ly for four equal quadrants.")
    cell_size = (Lx // 2) * (Ly // 2)

    labels = []

    def rec(prefix, remaining, cells_left):
        if cells_left == 1:
            if 0 <= remaining <= cell_size:
                labels.append(tuple(prefix + [remaining]))
            return
        for n in range(min(cell_size, remaining) + 1):
            rec(prefix + [n], remaining - n, cells_left - 1)

    rec([], Q, 4)
    labels = sorted(labels)
    label_to_id = {r: i for i, r in enumerate(labels)}

    site_quad = []
    for y in range(Ly):
        for x in range(Lx):
            site_quad.append(quadrant_of_site(x, y, Lx, Ly))

    macro_id = np.empty(len(basis), dtype=int)
    for ib, b in enumerate(basis):
        counts = [0, 0, 0, 0]
        for site in range(Lx * Ly):
            if (b >> site) & 1:
                counts[site_quad[site]] += 1
        macro_id[ib] = label_to_id[tuple(counts)]

    omega = np.array(
        [np.prod([math.comb(cell_size, n) for n in r]) for r in labels], dtype=float
    )
    pi = omega / np.sum(omega)

    group_counts = np.bincount(macro_id, minlength=len(labels))
    if not np.array_equal(group_counts, omega.astype(int)):
        raise RuntimeError("2D hard-core macro multiplicity mismatch.")

    return MacroData(labels=labels, macro_id=macro_id, omega=omega, pi=pi)


def hard_core_2d_left_half_initial_indices(
    basis: list[int], Lx: int, Ly: int, Q: int
):
    right_sites = []
    for y in range(Ly):
        for x in range(Lx // 2, Lx):
            right_sites.append(y * Lx + x)
    mask_right = sum(1 << j for j in right_sites)
    indices = [i for i, b in enumerate(basis) if (b & mask_right) == 0]
    expected = math.comb((Lx // 2) * Ly, Q)
    if len(indices) != expected:
        raise RuntimeError("Initial 2D hard-core class dimension mismatch.")
    return indices


# ============================================================
# Floquet circuit on the hard-core chain
# ============================================================


def build_hardcore_layer_hamiltonian(
    N: int,
    Q: int,
    bond_parity: int,
    hopping: float = J,
):
    basis, index = fixed_q_hardcore_basis(N, Q)
    rows, cols, vals = [], [], []
    for col, b in enumerate(basis):
        rows.append(col)
        cols.append(col)
        vals.append(0.0)
        for j in range(bond_parity, N - 1, 2):
            nj = (b >> j) & 1
            nk = (b >> (j + 1)) & 1
            if nj == nk:
                continue
            b2 = b ^ (1 << j) ^ (1 << (j + 1))
            rows.append(index[b2])
            cols.append(col)
            vals.append(-hopping)
    H = sp.csr_matrix(
        (vals, (rows, cols)), shape=(len(basis), len(basis)), dtype=np.complex128
    )
    return H, basis, index


def build_hardcore_interaction_diagonal(N: int, Q: int):
    basis, _ = fixed_q_hardcore_basis(N, Q)
    diag = np.zeros(len(basis), dtype=float)
    for i, b in enumerate(basis):
        diag[i] = sum(
            ((b >> j) & 1) * ((b >> (j + 1)) & 1) for j in range(N - 1)
        )
    return diag, basis


def floquet_action_factory(N: int, Q: int, theta_even: float, theta_odd: float, phi: float):
    H_even, basis, _ = build_hardcore_layer_hamiltonian(N, Q, bond_parity=0)
    H_odd, _, _ = build_hardcore_layer_hamiltonian(N, Q, bond_parity=1)
    diag_int, _ = build_hardcore_interaction_diagonal(N, Q)
    phase = np.exp(-1j * phi * diag_int)

    def action(X: np.ndarray):
        Y = expm_multiply(-1j * theta_even * H_even, X)
        Y = expm_multiply(-1j * theta_odd * H_odd, Y)
        Y = phase[:, None] * Y if Y.ndim == 2 else phase * Y
        return Y

    return action, basis


def analyze_floquet_class(
    N: int,
    Q: int,
    Kcells: int,
    periods: int,
    theta_even: float,
    theta_odd: float,
    phi: float,
):
    action, basis = floquet_action_factory(N, Q, theta_even, theta_odd, phi)
    macro = hard_core_1d_macro_data(basis, N, Q, Kcells)
    initial_indices = hard_core_left_half_initial_indices(basis, N, Q)

    dim = len(basis)
    psi = basis_columns(dim, initial_indices)
    p = np.zeros((periods + 1, len(macro.omega)), dtype=float)
    entropy = np.zeros(periods + 1, dtype=float)

    p[0] = macro_probabilities_from_columns(psi, macro)
    entropy[0] = coarse_entropy(p[0], macro.omega)

    for n in range(periods):
        psi = action(psi)
        p[n + 1] = macro_probabilities_from_columns(psi, macro)
        entropy[n + 1] = coarse_entropy(p[n + 1], macro.omega)

    S0 = entropy[0]
    Smax = math.log(float(np.sum(macro.omega)))
    sigma = (entropy - S0) / (Smax - S0)

    K = build_coarse_K_from_step(dim, macro, action)
    stoch_err, pi_err, min_entry = verify_K(K, macro.pi)
    print(
        "Floquet K checks:",
        f"stochasticity={stoch_err:.3e},",
        f"pi-preservation={pi_err:.3e},",
        f"min entry={min_entry:.3e}",
    )

    vpi = np.zeros(periods, dtype=float)
    eps = np.zeros(periods, dtype=float)
    ds_mix = np.zeros(periods, dtype=float)
    ds_corr = np.zeros(periods, dtype=float)

    for n in range(periods):
        vpi[n] = majorization_defect(p[n], p[n + 1], macro.pi)
        q0 = safe_normalize(K @ p[n])
        r = p[n + 1] - q0
        eps[n] = 0.5 * np.sum(np.abs(r))
        ds_mix[n] = coarse_entropy(q0, macro.omega) - coarse_entropy(p[n], macro.omega)
        ds_corr[n] = coarse_entropy(p[n + 1], macro.omega) - coarse_entropy(q0, macro.omega)

    i10, i90 = primary_window_indices(sigma)
    return {
        "periods": np.arange(periods + 1),
        "p": p,
        "entropy": entropy,
        "sigma": sigma,
        "vpi": vpi,
        "epsilon_hist": eps,
        "ds_mix": ds_mix,
        "ds_corr": ds_corr,
        "i10": i10,
        "i90": i90,
        "dim": dim,
        "initial_class_dim": len(initial_indices),
        "parameters": (theta_even, theta_odd, phi),
    }


# ============================================================
# Representative model calculations
# ============================================================


def run_1d_hardcore():
    def builder():
        N = 16 if not QUICK_TEST else 8
        Q = 2
        V1 = 1.0
        V2 = 0.7
        dt = DEFAULT_TAU
        tmax = 30.0 if not QUICK_TEST else 2.0
        times = np.arange(0.0, tmax + 0.5 * dt, dt)

        H, basis, _ = build_hardcore_1d_hamiltonian(N, Q, V1, V2)
        macro = hard_core_1d_macro_data(basis, N, Q, Kcells=4)
        init = hard_core_left_half_initial_indices(basis, N, Q)
        traj = analyze_time_independent_class(
            H,
            macro,
            init,
            times,
            tau=dt,
            compute_history_defect=True,
            metadata={"model": "1D hard-core", "N": N, "Q": Q, "V1": V1, "V2": V2},
        )
        return {"traj": traj, "macro": macro}

    return cached("model_1d_hardcore", builder)


def run_bose_hubbard():
    def builder():
        L = 8
        Q = 3 if not QUICK_TEST else 2
        U = 1.3
        dt = DEFAULT_TAU
        tmax = 30.0 if not QUICK_TEST else 2.0
        times = np.arange(0.0, tmax + 0.5 * dt, dt)

        H, basis, _ = build_bose_hubbard_hamiltonian(L, Q, U)
        macro = boson_1d_macro_data(basis, L, Q, Kcells=4)
        init = boson_left_half_initial_indices(basis, L, Q)
        traj = analyze_time_independent_class(
            H,
            macro,
            init,
            times,
            tau=dt,
            compute_history_defect=True,
            metadata={"model": "1D Bose-Hubbard", "L": L, "Q": Q, "U": U},
        )
        return {"traj": traj, "macro": macro}

    return cached("model_bose_hubbard", builder)


def run_2d_hardcore():
    def builder():
        Lx, Ly = 4, 4
        Q = 3 if not QUICK_TEST else 2
        V = 1.0
        dt = DEFAULT_TAU
        tmax = 30.0 if not QUICK_TEST else 1.5
        times = np.arange(0.0, tmax + 0.5 * dt, dt)

        H, basis, _, _ = build_hardcore_2d_hamiltonian(Lx, Ly, Q, V)
        macro = hard_core_2d_macro_data(basis, Lx, Ly, Q)
        init = hard_core_2d_left_half_initial_indices(basis, Lx, Ly, Q)
        traj = analyze_time_independent_class(
            H,
            macro,
            init,
            times,
            tau=dt,
            compute_history_defect=True,
            metadata={"model": "2D hard-core", "Lx": Lx, "Ly": Ly, "Q": Q, "V": V},
        )
        return {"traj": traj, "macro": macro}

    return cached("model_2d_hardcore", builder)


def run_hardcore_control_family():
    def builder():
        N = 16 if not QUICK_TEST else 8
        Q = 2
        dt = DEFAULT_TAU
        tmax = 30 if not QUICK_TEST else 4.0
        times = np.arange(0.0, tmax + 0.5 * dt, dt)

        # All three models use the same Hilbert sector, the same thermodynamic
        # preparation, and the same four-cell record. Only the closed dynamics changes.
        Hmix, basis, _ = build_hardcore_1d_hamiltonian(N, Q, 1.0, 0.7)
        Hfree, basis_free, _ = build_hardcore_1d_control_hamiltonian(N, Q, "free")
        Hret, basis_ret, _ = build_hardcore_1d_control_hamiltonian(N, Q, "engineered")
        if basis != basis_free or basis != basis_ret:
            raise RuntimeError("Control-family basis mismatch.")

        macro = hard_core_1d_macro_data(basis, N, Q, Kcells=4)
        init = hard_core_left_half_initial_indices(basis, N, Q)

        out = {}
        for name, H in [("mixing", Hmix), ("free", Hfree), ("engineered", Hret)]:
            out[name] = analyze_time_independent_class(
                H,
                macro,
                init,
                times,
                tau=dt,
                compute_history_defect=False,
                metadata={"model": name, "N": N, "Q": Q},
            )

        out["mirror_time"] = math.pi * N / (4.0 * J)
        return out

    return cached("hardcore_control_family", builder)


# ============================================================
# 1D hard-core parameter robustness scan
# ============================================================


def evaluate_parameter_point(N: int, Q: int, V1: float, V2: float, dt: float, tmax: float):
    H, basis, _ = build_hardcore_1d_hamiltonian(N, Q, V1, V2)
    macro = hard_core_1d_macro_data(basis, N, Q, Kcells=4)
    init = hard_core_left_half_initial_indices(basis, N, Q)
    times = np.arange(0.0, tmax + 0.5 * dt, dt)

    traj = analyze_time_independent_class(
        H,
        macro,
        init,
        times,
        tau=dt,
        compute_history_defect=False,
        metadata={"N": N, "Q": Q, "V1": V1, "V2": V2},
    )

    i10, i90 = traj.i10, traj.i90
    if i10 is None or i90 is None or i90 <= i10:
        return {
            "pass_fraction": np.nan,
            "max_vpi": np.nan,
            "min_rate": np.nan,
            "return_depth": np.nan,
            "t10": np.nan,
            "t90": np.nan,
        }

    # Pair indices corresponding to t in [t10,t90).
    pair_slice = slice(i10, i90)
    vv = traj.vpi[pair_slice]
    pass_fraction = float(np.mean(vv <= MAJ_TOL))
    max_vpi = float(np.max(vv))
    min_rate = float(np.min(traj.rate[i10 : i90 + 1]))

    return {
        "pass_fraction": pass_fraction,
        "max_vpi": max_vpi,
        "min_rate": min_rate,
        "return_depth": traj.metadata["return_depth"],
        "t10": float(traj.times[i10]),
        "t90": float(traj.times[i90]),
    }


def run_parameter_scan():
    def builder():
        N = 12 if not QUICK_TEST else 8
        Q = 3 if not QUICK_TEST else 2
        dt = 0.15 if not QUICK_TEST else 0.25
        tmax = 7.5 if not QUICK_TEST else 4.0

        if QUICK_TEST:
            V1_values = np.array([0.5, 1.0, 1.5])
            V2_values = np.array([0.0, 0.7, 1.2])
        else:
            V1_values = np.array([0.0, 0.25, 0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 2.00])
            V2_values = np.array([0.0, 0.25, 0.50, 0.70, 0.90, 1.20, 1.50])

        shape = (len(V2_values), len(V1_values))
        pass_fraction = np.full(shape, np.nan)
        max_vpi = np.full(shape, np.nan)
        min_rate = np.full(shape, np.nan)
        return_depth = np.full(shape, np.nan)
        t10 = np.full(shape, np.nan)
        t90 = np.full(shape, np.nan)

        total = len(V1_values) * len(V2_values)
        count = 0
        for iy, V2 in enumerate(V2_values):
            for ix, V1 in enumerate(V1_values):
                count += 1
                print(f"Parameter scan {count}/{total}: V1={V1:.2f}, V2={V2:.2f}")
                result = evaluate_parameter_point(N, Q, V1, V2, dt, tmax)
                pass_fraction[iy, ix] = result["pass_fraction"]
                max_vpi[iy, ix] = result["max_vpi"]
                min_rate[iy, ix] = result["min_rate"]
                return_depth[iy, ix] = result["return_depth"]
                t10[iy, ix] = result["t10"]
                t90[iy, ix] = result["t90"]

        return {
            "N": N,
            "Q": Q,
            "dt": dt,
            "tmax": tmax,
            "V1_values": V1_values,
            "V2_values": V2_values,
            "pass_fraction": pass_fraction,
            "max_vpi": max_vpi,
            "min_rate": min_rate,
            "return_depth": return_depth,
            "t10": t10,
            "t90": t90,
        }

    return cached("hardcore_parameter_scan", builder)

def run_boundary_dt_refinement():
    """
    Refine only the V1/J = 2 boundary points from the original parameter scan.

    The purpose is to separate three facts that should not be conflated:
    (i) the absolute finite-step defect V_pi becomes small when tau becomes small,
    (ii) exact relative majorization can nevertheless fail at individual steps, and
    (iii) the ordinary entropy-production rate can remain strictly positive.

    N, Q, V1, V2, tmax, and MAJ_TOL are held fixed. Only the observation step dt
    is changed.
    """

    def builder():
        N = 12
        Q = 3
        V1 = 2.0
        tmax = 7.5

        V2_values = np.array([0.0, 0.25, 0.50, 0.70, 0.90, 1.20, 1.50])
        dt_values = np.array([0.15, 0.075, 0.0375])

        rows = []

        print("\n" + "=" * 72)
        print("V1/J = 2 boundary time-step refinement")
        print("=" * 72)

        for dt in dt_values:
            for V2 in V2_values:
                print(
                    f"Boundary refinement: dt={dt:.4f}, "
                    f"V1={V1:.2f}, V2={V2:.2f}"
                )

                result = evaluate_parameter_point(
                    N=N,
                    Q=Q,
                    V1=V1,
                    V2=float(V2),
                    dt=float(dt),
                    tmax=tmax,
                )

                row = {
                    "dt": float(dt),
                    "V1": V1,
                    "V2": float(V2),
                    "pass_fraction": result["pass_fraction"],
                    "max_vpi": result["max_vpi"],
                    "min_rate": result["min_rate"],
                    "return_depth": result["return_depth"],
                    "t10": result["t10"],
                    "t90": result["t90"],
                }
                rows.append(row)

                print(f"    pass fraction = {row['pass_fraction']:.12g}")
                print(f"    max V_pi      = {row['max_vpi']:.12g}")
                print(f"    min rate      = {row['min_rate']:.12g}")

        return {
            "N": N,
            "Q": Q,
            "V1": V1,
            "tmax": tmax,
            "V2_values": V2_values,
            "dt_values": dt_values,
            "rows": rows,
        }

    data = cached("hardcore_boundary_dt_refinement", builder)

    csv_path = DATA_DIR / "hardcore_boundary_dt_refinement.csv"
    with csv_path.open("w", encoding="utf-8") as f:
        f.write(
            "dt,V1_over_J,V2_over_J,pass_fraction,max_Vpi,min_rate,"
            "return_depth,t10,t90\n"
        )
        for row in data["rows"]:
            f.write(
                f"{row['dt']},{row['V1']},{row['V2']},"
                f"{row['pass_fraction']},{row['max_vpi']},{row['min_rate']},"
                f"{row['return_depth']},{row['t10']},{row['t90']}\n"
            )
    print(f"Saved: {csv_path}")

    print("\nBoundary-refinement summary by dt")
    print("-" * 72)
    for dt in data["dt_values"]:
        subset = [r for r in data["rows"] if np.isclose(r["dt"], dt)]
        pass_values = np.array([r["pass_fraction"] for r in subset], dtype=float)
        vpi_values = np.array([r["max_vpi"] for r in subset], dtype=float)
        rate_values = np.array([r["min_rate"] for r in subset], dtype=float)
        print(
            f"dt = {dt:.4f}: "
            f"min pass fraction = {np.nanmin(pass_values):.12g}, "
            f"max V_pi = {np.nanmax(vpi_values):.12g}, "
            f"min rate = {np.nanmin(rate_values):.12g}"
        )

    return data


def select_local_defect_reference_time(
    N: int,
    Q: int,
    V1: float,
    V2: float,
    scout_dt: float = 0.15,
    tmax: float = 7.5,
):
    """
    Choose one fixed physical time for the local defect-rate refinement.

    The reference time is selected once from the original scout resolution as the
    time inside the primary 10%-90% window at which the finite-step V_pi is largest.
    The same physical t_ref is then held fixed while tau is reduced. This avoids
    confusing a changing time grid with genuine tau-scaling.
    """
    H, basis, _ = build_hardcore_1d_hamiltonian(N, Q, V1, V2)
    macro = hard_core_1d_macro_data(basis, N, Q, Kcells=4)
    init = hard_core_left_half_initial_indices(basis, N, Q)
    times = np.arange(0.0, tmax + 0.5 * scout_dt, scout_dt)

    traj = analyze_time_independent_class(
        H,
        macro,
        init,
        times,
        tau=scout_dt,
        compute_history_defect=False,
        metadata={"N": N, "Q": Q, "V1": V1, "V2": V2},
    )

    if traj.i10 is None or traj.i90 is None or traj.i90 <= traj.i10:
        raise RuntimeError("Could not identify the primary relaxation window.")

    local = traj.vpi[traj.i10 : traj.i90]
    rel_idx = int(np.argmax(local))
    idx = traj.i10 + rel_idx

    return {
        "t_ref": float(traj.times[idx]),
        "scout_vpi": float(traj.vpi[idx]),
        "sigma_ref": float(traj.sigma[idx]),
        "instantaneous_rate_ref": float(traj.rate[idx]),
        "t10": float(traj.times[traj.i10]),
        "t90": float(traj.times[traj.i90]),
    }


def evaluate_fixed_time_defect_scaling(
    N: int,
    Q: int,
    V1: float,
    V2: float,
    t_ref: float,
    tau_values: np.ndarray,
):
    """
    Evaluate V_pi(t_ref -> t_ref+tau) at one fixed physical time.

    We report both the absolute defect and the finite-step defect-rate proxy

        nu_pi(t_ref; tau) = V_pi(t_ref -> t_ref+tau) / tau.

    We also compute the finite-step entropy slope

        [S_R(t_ref+tau)-S_R(t_ref)] / tau

    and the exact instantaneous entropy rate dot S_R(t_ref). The latter is obtained
    directly from the Schrodinger equation, not by finite differences.
    """
    H, basis, _ = build_hardcore_1d_hamiltonian(N, Q, V1, V2)
    macro = hard_core_1d_macro_data(basis, N, Q, Kcells=4)
    init = hard_core_left_half_initial_indices(basis, N, Q)

    psi0 = basis_columns(len(basis), init)
    if abs(t_ref) < 1e-15:
        psi_t = psi0.copy()
    else:
        psi_t = expm_multiply(-1j * H * t_ref, psi0)

    p_t = macro_probabilities_from_columns(psi_t, macro)
    S_t = coarse_entropy(p_t, macro.omega)
    dp_t = macro_rate_from_columns(psi_t, H, macro)
    rate_t = entropy_rate_from_dp(p_t, dp_t, macro.omega)

    rows = []
    for tau in np.asarray(tau_values, dtype=float):
        psi_q = expm_multiply(-1j * H * tau, psi_t)
        p_q = macro_probabilities_from_columns(psi_q, macro)
        S_q = coarse_entropy(p_q, macro.omega)
        vpi = majorization_defect(p_t, p_q, macro.pi)
        margin = lorenz_margin(p_t, p_q, macro.pi)
        dS = S_q - S_t

        rows.append(
            {
                "tau": float(tau),
                "vpi": float(vpi),
                "nu_pi": float(vpi / tau),
                "lorenz_margin": float(margin),
                "dS": float(dS),
                "finite_entropy_rate": float(dS / tau),
                "instantaneous_entropy_rate": float(rate_t),
            }
        )

    return {
        "N": N,
        "Q": Q,
        "V1": V1,
        "V2": V2,
        "t_ref": float(t_ref),
        "p_ref": p_t,
        "S_ref": float(S_t),
        "instantaneous_entropy_rate": float(rate_t),
        "rows": rows,
    }


def run_local_defect_rate_analysis():
    """
    Fixed-time tau-refinement on selected strong-coupling boundary points.

    The selected V2 values sample the boundary where the original parameter scan
    exhibits tiny but genuine failures of the stronger relative-majorization order
    while the coarse entropy-production rate stays positive.
    """

    def builder():
        N = 12
        Q = 3
        V1 = 2.0
        tmax = 7.5
        scout_dt = 0.15
        V2_values = np.array([0.70, 0.90, 1.20])
        tau_values = np.array([0.15, 0.075, 0.0375, 0.01875, 0.009375])

        cases = []
        for V2 in V2_values:
            print("\n" + "=" * 72)
            print(f"Fixed-time local defect refinement: V1={V1:.2f}, V2={V2:.2f}")
            print("=" * 72)

            ref = select_local_defect_reference_time(
                N=N,
                Q=Q,
                V1=V1,
                V2=float(V2),
                scout_dt=scout_dt,
                tmax=tmax,
            )
            result = evaluate_fixed_time_defect_scaling(
                N=N,
                Q=Q,
                V1=V1,
                V2=float(V2),
                t_ref=ref["t_ref"],
                tau_values=tau_values,
            )
            result["reference_selection"] = ref
            cases.append(result)

            print(f"t_ref = {result['t_ref']:.8g}")
            print(
                "instantaneous rate =",
                f"{result['instantaneous_entropy_rate']:.12g}",
            )
            for row in result["rows"]:
                print(
                    f"tau={row['tau']:.8g}: "
                    f"V_pi={row['vpi']:.12g}, "
                    f"V_pi/tau={row['nu_pi']:.12g}, "
                    f"DeltaS/tau={row['finite_entropy_rate']:.12g}"
                )

        return {
            "N": N,
            "Q": Q,
            "V1": V1,
            "tmax": tmax,
            "scout_dt": scout_dt,
            "V2_values": V2_values,
            "tau_values": tau_values,
            "cases": cases,
        }

    data = cached("hardcore_local_defect_rate", builder)

    csv_path = DATA_DIR / "hardcore_local_defect_rate.csv"
    with csv_path.open("w", encoding="utf-8") as f:
        f.write(
            "V1_over_J,V2_over_J,t_ref,tau,V_pi,V_pi_over_tau,"
            "lorenz_margin,DeltaS_over_kB,finite_entropy_rate,"
            "instantaneous_entropy_rate\n"
        )
        for case in data["cases"]:
            for row in case["rows"]:
                f.write(
                    f"{case['V1']},{case['V2']},{case['t_ref']},{row['tau']},"
                    f"{row['vpi']},{row['nu_pi']},{row['lorenz_margin']},"
                    f"{row['dS']},{row['finite_entropy_rate']},"
                    f"{row['instantaneous_entropy_rate']}\n"
                )
    print(f"Saved: {csv_path}")

    return data


# ============================================================
# Exact free-expansion counting: hard-core versus bosons
# ============================================================


def statistics_limit_data():
    # Genuine dilute thermodynamic sequence: Li=M^2, Q=M, Lf=2Li.
    M_values = np.arange(2, 41 if not QUICK_TEST else 10)
    rho = []
    hc_ratio = []
    boson_ratio = []

    for M in M_values:
        Li = int(M * M)
        Lf = 2 * Li
        Q = int(M)
        rho.append(Q / Li)

        dS_hc = log_binom(Lf, Q) - log_binom(Li, Q)
        dS_b = log_multichoose(Lf, Q) - log_multichoose(Li, Q)
        classical = Q * math.log(2.0)
        hc_ratio.append(dS_hc / classical)
        boson_ratio.append(dS_b / classical)

    # General volume ratio at a low fixed density sequence.
    lambdas = np.array([1.25, 1.5, 2.0, 3.0, 4.0])
    Q_general = 8
    Li_general = 400
    general_hc = []
    general_b = []
    for lam in lambdas:
        Lf = int(round(lam * Li_general))
        general_hc.append(
            (log_binom(Lf, Q_general) - log_binom(Li_general, Q_general)) / Q_general
        )
        general_b.append(
            (log_multichoose(Lf, Q_general) - log_multichoose(Li_general, Q_general)) / Q_general
        )

    return {
        "M": M_values,
        "rho": np.asarray(rho),
        "hc_ratio": np.asarray(hc_ratio),
        "boson_ratio": np.asarray(boson_ratio),
        "lambdas": lambdas,
        "ln_lambda": np.log(lambdas),
        "general_hc": np.asarray(general_hc),
        "general_boson": np.asarray(general_b),
    }


# ============================================================
# Plot helpers
# ============================================================


def primary_mask_for_pairs(traj: Trajectory):
    mask = np.zeros(len(traj.vpi), dtype=bool)
    if traj.i10 is not None and traj.i90 is not None and traj.i90 > traj.i10:
        mask[traj.i10 : traj.i90] = True
    return mask


def print_trajectory_summary(name: str, traj: Trajectory):
    print("\n" + "=" * 72)
    print(name)
    print("=" * 72)
    print("metadata:", traj.metadata)
    if traj.i10 is not None and traj.i90 is not None:
        print(
            f"primary window: t={traj.times[traj.i10]:.3f} -> {traj.times[traj.i90]:.3f}"
        )
        print(
            "min primary rate =",
            f"{np.min(traj.rate[traj.i10:traj.i90+1]):.12g}",
        )
        print(
            "max primary V_pi =",
            f"{np.max(traj.vpi[traj.i10:traj.i90]):.12g}",
        )
        print(
            "relative-majorization pass fraction =",
            f"{np.mean(traj.vpi[traj.i10:traj.i90] <= MAJ_TOL):.6f}",
        )
        if traj.epsilon_hist is not None:
            print(
                "max primary epsilon_hist =",
                f"{np.max(traj.epsilon_hist[traj.i10:traj.i90]):.12g}",
            )
    print("max Sigma =", f"{np.max(traj.sigma):.12g}")
    print("post-relaxation return depth =", traj.metadata.get("return_depth"))


def plot_cross_model_generality(hc: Trajectory, bh: Trajectory, d2: Trajectory):
    models = [hc, bh, d2]
    labels = ["1D hard-core", "1D Bose-Hubbard", "2D hard-core"]
    colors = [RED, BLUE, GREEN]

    fig, axes = plt.subplots(2, 3, figsize=(8.2, 4.6), sharex="col")

    for col, (traj, label, color) in enumerate(zip(models, labels, colors)):
        ax = axes[0, col]
        ax.plot(traj.times, traj.sigma, color=color)
        ax.axhline(1.0, color=GRAY, linestyle=":", linewidth=1.2)
        if traj.i10 is not None and traj.i90 is not None:
            ax.axvspan(
                traj.times[traj.i10],
                traj.times[traj.i90],
                color=color,
                alpha=0.08,
                linewidth=0,
            )
        ax.set_ylabel(r"$\Sigma_R$" if col == 0 else "")
        ax.text(0.97, 0.08, label, transform=ax.transAxes, ha="right", va="bottom")
        finish_axes(ax)
        panel_label(ax, f"({chr(ord('a') + col)})")

        ax = axes[1, col]
        tpair = traj.times[:-1]
        ax.semilogy(tpair, np.maximum(traj.vpi, 1e-16), color=color, label=r"$\mathcal{V}_\pi$")
        if traj.epsilon_hist is not None:
            ax.semilogy(
                tpair,
                np.maximum(traj.epsilon_hist, 1e-16),
                color=BLACK,
                linestyle="--",
                linewidth=1.2,
                label=r"$\epsilon_{\rm hist}$",
            )
        ax.axhline(1e-12, color=GRAY, linestyle=":", linewidth=1.0)
        ax.set_xlabel(r"$Jt$")
        ax.set_xlim(0, 30)
        ax.set_ylabel(r"return diagnostic" if col == 0 else "")
        if col == 2:
            ax.legend(loc="best")
        finish_axes(ax)
        panel_label(ax, f"({chr(ord('d') + col)})")

    savefig(fig, "generality_three_models.pdf", h_pad=0.45, w_pad=0.1)


def plot_history_activity_generality(bh: Trajectory, d2: Trajectory):
    fig, axes = plt.subplots(1, 2, figsize=(7.8, 2.7))
    for ax, traj, color, label, pchar in [
        (axes[0], bh, BLUE, "1D Bose-Hubbard", "(a)"),
        (axes[1], d2, GREEN, "2D hard-core", "(b)"),
    ]:
        tpair = traj.times[:-1]
        ax.semilogy(
            tpair,
            np.maximum(traj.epsilon_hist, 1e-16),
            color=BLACK,
            linestyle="--",
            label=r"$\epsilon_{\rm hist}$",
        )
        ax.semilogy(
            tpair,
            np.maximum(traj.vpi, 1e-16),
            color=color,
            label=r"$\mathcal{V}_\pi$",
        )
        if traj.i10 is not None and traj.i90 is not None:
            ax.axvspan(
                traj.times[traj.i10],
                traj.times[traj.i90],
                color=color,
                alpha=0.08,
                linewidth=0,
            )
        ax.axhline(1e-12, color=GRAY, linestyle=":", linewidth=1.0)
        ax.set_xlabel(r"$Jt$")
        ax.set_xlim(0, 30)
        ax.set_ylabel(r"history / return magnitude")
        ax.text(0.97, 0.08, label, transform=ax.transAxes, ha="right", va="bottom")
        ax.legend(loc="best")
        finish_axes(ax)
        panel_label(ax, pchar)
    savefig(fig, "generality_history_activity.pdf", w_pad=0.5)


def plot_control_family(control: dict):
    fig, axes = plt.subplots(1, 2, figsize=(7.8, 2.7))

    styles = [
        ("mixing", RED, "-", "mixing"),
        ("free", BLUE, "--", "free"),
        ("engineered", GREEN, "-.", "engineered return"),
    ]

    for key, color, ls, label in styles:
        traj = control[key]
        axes[0].plot(traj.times, traj.sigma, color=color, linestyle=ls, label=label)
        axes[1].semilogy(
            traj.times[:-1],
            np.maximum(traj.vpi, 1e-16),
            color=color,
            linestyle=ls,
            label=label,
        )

    axes[0].axhline(1.0, color=GRAY, linestyle=":", linewidth=1.2)
    axes[0].axvline(control["mirror_time"], color=GRAY, linestyle=":", linewidth=1.2)
    axes[0].set_xlabel(r"$Jt$")
    axes[0].set_ylabel(r"$\Sigma_R$")
    axes[0].legend(loc="best")
    finish_axes(axes[0])
    panel_label(axes[0], "(a)")

    axes[1].axhline(1e-12, color=GRAY, linestyle=":", linewidth=1.0)
    axes[1].axvline(control["mirror_time"], color=GRAY, linestyle=":", linewidth=1.2)
    axes[1].set_xlabel(r"$Jt$")
    axes[1].set_ylabel(r"$\mathcal{V}_\pi$")
    axes[1].legend(loc="best")
    finish_axes(axes[1])
    panel_label(axes[1], "(b)")

    savefig(fig, "hardcore_control_family.pdf", w_pad=0.4)


def plot_parameter_scan(scan: dict):
    V1_values = scan["V1_values"]
    V2_values = scan["V2_values"]
    X, Y = np.meshgrid(V1_values, V2_values)

    fig, axes = plt.subplots(1, 3, figsize=(6.8, 2.7))

    m0 = axes[0].pcolormesh(X, Y, scan["pass_fraction"], shading="nearest", vmin=0, vmax=1)
    cb0 = fig.colorbar(m0, ax=axes[0], pad=0.02)
    cb0.set_label(r"pass fraction")
    axes[0].set_xlabel(r"$V_1/J$")
    axes[0].set_ylabel(r"$V_2/J$")
    axes[0].plot([1.0], [0.7], marker="x", color=BLACK, markersize=6, mew=1.2)
    finish_axes(axes[0])
    panel_label(axes[0], "(a)")

    logv = np.log10(np.maximum(scan["max_vpi"], 1e-16))
    m1 = axes[1].pcolormesh(X, Y, logv, shading="nearest")
    cb1 = fig.colorbar(m1, ax=axes[1], pad=0.02)
    cb1.set_label(r"$\log_{10}\max\mathcal{V}_\pi$")
    axes[1].set_xlabel(r"$V_1/J$")
    axes[1].set_ylabel(r"$V_2/J$")
    axes[1].plot([1.0], [0.7], marker="x", color=BLACK, markersize=6, mew=1.2)
    finish_axes(axes[1])
    panel_label(axes[1], "(b)")

    m2 = axes[2].pcolormesh(X, Y, scan["min_rate"], shading="nearest")
    cb2 = fig.colorbar(m2, ax=axes[2], pad=0.02)
    cb2.set_label(r"$\min\dot S_R/(k_{\rm B}J)$")
    axes[2].set_xlabel(r"$V_1/J$")
    axes[2].set_ylabel(r"$V_2/J$")
    axes[2].plot([1.0], [0.7], marker="x", color=BLACK, markersize=6, mew=1.2)
    finish_axes(axes[2])
    panel_label(axes[2], "(c)")

    savefig(fig, "hardcore_parameter_robustness.pdf", w_pad=0.35)


def plot_boundary_dt_refinement(data: dict):
    """Three-panel refinement map along the V1/J=2 strong-coupling boundary."""
    dt_values = np.asarray(data["dt_values"], dtype=float)
    V2_values = np.asarray(data["V2_values"], dtype=float)

    shape = (len(V2_values), len(dt_values))
    pass_fraction = np.full(shape, np.nan)
    max_vpi = np.full(shape, np.nan)
    min_rate = np.full(shape, np.nan)

    dt_to_ix = {float(v): i for i, v in enumerate(dt_values)}
    v2_to_iy = {float(v): i for i, v in enumerate(V2_values)}
    for row in data["rows"]:
        ix = dt_to_ix[float(row["dt"])]
        iy = v2_to_iy[float(row["V2"])]
        pass_fraction[iy, ix] = row["pass_fraction"]
        max_vpi[iy, ix] = row["max_vpi"]
        min_rate[iy, ix] = row["min_rate"]

    X, Y = np.meshgrid(dt_values, V2_values)
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 2.8))

    m0 = axes[0].pcolormesh(X, Y, pass_fraction, shading="nearest", vmin=0.90, vmax=1.0)
    cb0 = fig.colorbar(m0, ax=axes[0], pad=0.02)
    cb0.set_label("pass fraction")
    axes[0].set_xlabel(r"$J\tau$")
    axes[0].set_xticks(dt_values)
    axes[0].set_xticklabels(["0.038", "0.075", "0.150"], rotation=35, ha="right")
    axes[0].set_ylabel(r"$V_2/J$")
    finish_axes(axes[0])
    panel_label(axes[0], "(a)")

    logv = np.log10(np.maximum(max_vpi, 1e-16))
    m1 = axes[1].pcolormesh(X, Y, logv, shading="nearest")
    cb1 = fig.colorbar(m1, ax=axes[1], pad=0.02)
    cb1.set_label(r"$\log_{10}\max\mathcal{V}_\pi$")
    axes[1].set_xlabel(r"$J\tau$")
    axes[1].set_xticks(dt_values)
    axes[1].set_xticklabels(["0.038", "0.075", "0.150"], rotation=35, ha="right")
    axes[1].set_ylabel(r"$V_2/J$")
    finish_axes(axes[1])
    panel_label(axes[1], "(b)")

    m2 = axes[2].pcolormesh(X, Y, min_rate, shading="nearest")
    cb2 = fig.colorbar(m2, ax=axes[2], pad=0.02)
    cb2.set_label(r"$\min\dot S_R/(k_{\rm B}J)$")
    axes[2].set_xlabel(r"$J\tau$")
    axes[2].set_xticks(dt_values)
    axes[2].set_xticklabels(["0.038", "0.075", "0.150"], rotation=35, ha="right")
    axes[2].set_ylabel(r"$V_2/J$")
    finish_axes(axes[2])
    panel_label(axes[2], "(c)")

    savefig(fig, "hardcore_boundary_dt_refinement.pdf", w_pad=0.35)


def plot_local_defect_rate(data: dict):
    """
    Fixed-time local refinement of the stronger relative-majorization defect.

    Panel (a) shows the finite-step defect-rate proxy V_pi/tau. A nonzero limiting
    trend means the stronger local order can fail even though V_pi itself vanishes
    linearly as tau -> 0.

    Panel (b) compares the finite-step entropy slope with the exact instantaneous
    entropy rate at the same fixed physical time. Positive values demonstrate that
    failure of the stronger order need not imply entropy decrease.
    """
    colors = [RED, BLUE, GREEN]
    markers = ["o", "s", "^"]

    fig, axes = plt.subplots(1, 2, figsize=(6.8, 2.7))

    for color, marker, case in zip(colors, markers, data["cases"]):
        rows = sorted(case["rows"], key=lambda r: r["tau"])
        tau = np.array([r["tau"] for r in rows], dtype=float)
        nu = np.array([r["nu_pi"] for r in rows], dtype=float)
        slope = np.array([r["finite_entropy_rate"] for r in rows], dtype=float)
        rate0 = float(case["instantaneous_entropy_rate"])
        label = rf"$V_2/J={case['V2']:.1f}$"

        axes[0].semilogy(tau, np.maximum(nu, 1e-16), marker=marker, color=color, label=label)

        x_entropy = np.concatenate([[0.0], tau])
        y_entropy = np.concatenate([[rate0], slope])
        axes[1].plot(x_entropy, y_entropy, marker=marker, color=color, label=label)
        axes[1].scatter([0.0], [rate0], marker="*", s=42, color=color, zorder=5)

    axes[0].set_xlabel(r"$J\tau$")
    axes[0].set_ylabel(r"$\mathcal{V}_\pi/(J\tau)$")
    axes[0].legend(loc="best")
    finish_axes(axes[0])
    panel_label(axes[0], "(a)")

    axes[1].axhline(0.0, color=GRAY, linestyle=":", linewidth=1.2)
    axes[1].set_xlabel(r"$J\tau$")
    axes[1].set_ylabel(r"$\Delta_\tau S_R/(k_{\rm B}J\tau)$")
    axes[1].legend(loc="best")
    finish_axes(axes[1])
    panel_label(axes[1], "(b)")

    savefig(fig, "hardcore_local_defect_rate.pdf", w_pad=0.5)


def plot_local_defect_absolute_scaling(data: dict):
    """Supplementary log-log view of the absolute V_pi scaling at fixed t_ref."""
    colors = [RED, BLUE, GREEN]
    markers = ["o", "s", "^"]

    fig, ax = plt.subplots(figsize=(4.3, 3.0))
    for color, marker, case in zip(colors, markers, data["cases"]):
        rows = sorted(case["rows"], key=lambda r: r["tau"])
        tau = np.array([r["tau"] for r in rows], dtype=float)
        vpi = np.array([r["vpi"] for r in rows], dtype=float)
        ax.loglog(
            tau,
            np.maximum(vpi, 1e-18),
            marker=marker,
            color=color,
            label=rf"$V_2/J={case['V2']:.1f}$",
        )

    # A slope-one guide anchored to the case with the largest small-tau defect rate.
    case0 = max(
        data["cases"],
        key=lambda c: sorted(c["rows"], key=lambda r: r["tau"])[0]["nu_pi"],
    )
    rows0 = sorted(case0["rows"], key=lambda r: r["tau"])
    tau0 = float(rows0[0]["tau"])
    v0 = max(float(rows0[0]["vpi"]), 1e-18)
    guide_tau = np.array([tau0, max(r["tau"] for r in rows0)], dtype=float)
    guide_v = v0 * guide_tau / tau0
    ax.loglog(guide_tau, guide_v, color=BLACK, linestyle=":", linewidth=1.2, label=r"$\propto\tau$")

    ax.set_xlabel(r"$J\tau$")
    ax.set_ylabel(r"$\mathcal{V}_\pi$")
    ax.legend(loc="best")
    finish_axes(ax)
    savefig(fig, "hardcore_local_defect_absolute_scaling.pdf")


def plot_statistics_limit(data: dict):
    fig, axes = plt.subplots(1, 2, figsize=(6.8, 2.7))

    order = np.argsort(data["rho"])
    axes[0].plot(
        data["rho"][order],
        data["hc_ratio"][order],
        marker="o",
        color=RED,
        label="hard-core",
    )
    axes[0].plot(
        data["rho"][order],
        data["boson_ratio"][order],
        marker="s",
        color=BLUE,
        label="bosonic",
    )
    axes[0].axhline(1.0, color=BLACK, linestyle=":", linewidth=1.2, label="classical")
    axes[0].set_xlabel(r"$Q/L_i$")
    axes[0].set_ylabel(r"$\Delta S_R/(Qk_{\rm B}\ln 2)$")
    axes[0].legend(loc="best")
    finish_axes(axes[0])
    panel_label(axes[0], "(a)")

    axes[1].plot(
        data["ln_lambda"],
        data["general_hc"],
        marker="o",
        color=RED,
        label="hard-core",
    )
    axes[1].plot(
        data["ln_lambda"],
        data["general_boson"],
        marker="s",
        color=BLUE,
        label="bosonic",
    )
    xmin = float(np.min(data["ln_lambda"]))
    xmax = float(np.max(data["ln_lambda"]))
    axes[1].plot([xmin, xmax], [xmin, xmax], color=BLACK, linestyle=":", linewidth=1.2)
    axes[1].set_xlabel(r"$\ln(L_f/L_i)$")
    axes[1].set_ylabel(r"$\Delta S_R/(Qk_{\rm B})$")
    axes[1].legend(loc="best")
    finish_axes(axes[1])
    panel_label(axes[1], "(b)")

    savefig(fig, "statistics_and_classical_limit.pdf", w_pad=0.5)


def plot_floquet(data: dict):
    n = data["periods"]
    fig, axes = plt.subplots(1, 2, figsize=(6.8, 2.7))

    axes[0].plot(n, data["sigma"], color=PURPLE)
    axes[0].axhline(1.0, color=GRAY, linestyle=":", linewidth=1.2)
    if data["i10"] is not None and data["i90"] is not None:
        axes[0].axvspan(data["i10"], data["i90"], color=PURPLE, alpha=0.08, linewidth=0)
    axes[0].set_xlabel(r"Floquet period $n$")
    axes[0].set_ylabel(r"$\Sigma_R$")
    finish_axes(axes[0])
    panel_label(axes[0], "(a)")

    steps = n[:-1]
    axes[1].semilogy(steps, np.maximum(data["epsilon_hist"], 1e-16), color=BLACK, linestyle="--", label=r"$\epsilon_{\rm hist}$")
    axes[1].semilogy(steps, np.maximum(data["vpi"], 1e-16), color=PURPLE, label=r"$\mathcal{V}_\pi$")
    axes[1].axhline(1e-12, color=GRAY, linestyle=":", linewidth=1.0)
    axes[1].set_xlabel(r"Floquet period $n$")
    axes[1].set_ylabel(r"history / return magnitude")
    axes[1].legend(loc="best")
    finish_axes(axes[1])
    panel_label(axes[1], "(b)")

    savefig(fig, "floquet_generality.pdf", w_pad=0.5)


# ============================================================
# Text/CSV summaries
# ============================================================


def save_summary(hc=None, bh=None, d2=None, control=None, scan=None, floquet=None, boundary=None, local_defect=None):
    lines = []
    lines.append("Generality tests for closed-system thermodynamic irreversibility\n")
    lines.append("All entropies are in units of k_B.\n")

    def add_traj(name, traj: Trajectory):
        lines.append(f"\n{name}\n")
        lines.append("-" * len(name) + "\n")
        lines.append(f"metadata = {traj.metadata}\n")
        if traj.i10 is not None and traj.i90 is not None:
            lines.append(
                f"primary window = {traj.times[traj.i10]:.8g} -> {traj.times[traj.i90]:.8g}\n"
            )
            lines.append(
                f"min primary rate = {np.min(traj.rate[traj.i10:traj.i90+1]):.12g}\n"
            )
            lines.append(
                f"max primary V_pi = {np.max(traj.vpi[traj.i10:traj.i90]):.12g}\n"
            )
            lines.append(
                f"majorization pass fraction = {np.mean(traj.vpi[traj.i10:traj.i90] <= MAJ_TOL):.12g}\n"
            )
            if traj.epsilon_hist is not None:
                lines.append(
                    f"max primary epsilon_hist = {np.max(traj.epsilon_hist[traj.i10:traj.i90]):.12g}\n"
                )
        lines.append(f"max Sigma = {np.max(traj.sigma):.12g}\n")
        lines.append(f"post-relaxation return depth = {traj.metadata.get('return_depth')}\n")

    if hc is not None:
        add_traj("1D interacting hard-core", hc)
    if bh is not None:
        add_traj("1D Bose-Hubbard", bh)
    if d2 is not None:
        add_traj("2D interacting hard-core", d2)

    if control is not None:
        lines.append("\nHard-core control family\n")
        lines.append("------------------------\n")
        lines.append(f"mirror time = {control['mirror_time']:.12g}\n")
        for key in ("mixing", "free", "engineered"):
            traj = control[key]
            lines.append(f"{key}: max Sigma = {np.max(traj.sigma):.12g}, max V_pi = {np.max(traj.vpi):.12g}\n")

    if scan is not None:
        valid = np.isfinite(scan["pass_fraction"])
        lines.append("\nHard-core parameter scan\n")
        lines.append("------------------------\n")
        lines.append(f"N={scan['N']}, Q={scan['Q']}, dt={scan['dt']}, tmax={scan['tmax']}\n")
        if np.any(valid):
            lines.append(
                f"fraction of valid grid points with pass fraction 1 = {np.mean(scan['pass_fraction'][valid] >= 1.0 - 1e-12):.12g}\n"
            )
            lines.append(
                f"median pass fraction = {np.nanmedian(scan['pass_fraction']):.12g}\n"
            )
            lines.append(
                f"maximum primary V_pi over grid = {np.nanmax(scan['max_vpi']):.12g}\n"
            )
            lines.append(
                f"minimum primary entropy rate over grid = {np.nanmin(scan['min_rate']):.12g}\n"
            )

    if floquet is not None:
        lines.append("\nFloquet test\n")
        lines.append("------------\n")
        lines.append(f"dim = {floquet['dim']}\n")
        lines.append(f"initial class dim = {floquet['initial_class_dim']}\n")
        lines.append(f"parameters = {floquet['parameters']}\n")
        if floquet["i10"] is not None and floquet["i90"] is not None:
            sl = slice(floquet["i10"], floquet["i90"])
            lines.append(f"max primary V_pi = {np.max(floquet['vpi'][sl]):.12g}\n")
            lines.append(f"max primary epsilon_hist = {np.max(floquet['epsilon_hist'][sl]):.12g}\n")

    if boundary is not None:
        lines.append("\nStrong-coupling boundary time-step refinement\n")
        lines.append("---------------------------------------------\n")
        lines.append(
            f"N={boundary['N']}, Q={boundary['Q']}, V1/J={boundary['V1']}, "
            f"tmax={boundary['tmax']}\n"
        )
        for dt in boundary["dt_values"]:
            subset = [r for r in boundary["rows"] if np.isclose(r["dt"], dt)]
            lines.append(
                f"dt={dt:.8g}: min pass fraction={np.nanmin([r['pass_fraction'] for r in subset]):.12g}, "
                f"max V_pi={np.nanmax([r['max_vpi'] for r in subset]):.12g}, "
                f"min entropy rate={np.nanmin([r['min_rate'] for r in subset]):.12g}\n"
            )

    if local_defect is not None:
        lines.append("\nFixed-time local relative-majorization defect-rate refinement\n")
        lines.append("---------------------------------------------------------\n")
        for case in local_defect["cases"]:
            lines.append(
                f"V1/J={case['V1']}, V2/J={case['V2']}, t_ref={case['t_ref']:.12g}, "
                f"instantaneous entropy rate={case['instantaneous_entropy_rate']:.12g}\n"
            )
            for row in sorted(case["rows"], key=lambda r: r["tau"], reverse=True):
                lines.append(
                    f"  tau={row['tau']:.12g}, V_pi={row['vpi']:.12g}, "
                    f"V_pi/tau={row['nu_pi']:.12g}, DeltaS/tau={row['finite_entropy_rate']:.12g}\n"
                )

    path = DATA_DIR / "generality_summary.txt"
    path.write_text("".join(lines), encoding="utf-8")
    print(f"Saved: {path}")

    if scan is not None:
        csv_path = DATA_DIR / "hardcore_parameter_scan.csv"
        with csv_path.open("w", encoding="utf-8") as f:
            f.write("V1_over_J,V2_over_J,pass_fraction,max_Vpi,min_rate,return_depth,t10,t90\n")
            for iy, V2 in enumerate(scan["V2_values"]):
                for ix, V1 in enumerate(scan["V1_values"]):
                    f.write(
                        f"{V1},{V2},{scan['pass_fraction'][iy,ix]},{scan['max_vpi'][iy,ix]},"
                        f"{scan['min_rate'][iy,ix]},{scan['return_depth'][iy,ix]},"
                        f"{scan['t10'][iy,ix]},{scan['t90'][iy,ix]}\n"
                    )
        print(f"Saved: {csv_path}")


# ============================================================
# Main
# ============================================================


def main():
    hc_data = run_1d_hardcore() if RUN_1D_HARDCORE else None
    bh_data = run_bose_hubbard() if RUN_BOSE_HUBBARD else None
    d2_data = run_2d_hardcore() if RUN_2D_HARDCORE else None

    hc = hc_data["traj"] if hc_data else None
    bh = bh_data["traj"] if bh_data else None
    d2 = d2_data["traj"] if d2_data else None

    if hc is not None:
        print_trajectory_summary("1D interacting hard-core", hc)
    if bh is not None:
        print_trajectory_summary("1D Bose-Hubbard", bh)
    if d2 is not None:
        print_trajectory_summary("2D interacting hard-core", d2)

    if hc is not None and bh is not None and d2 is not None:
        plot_cross_model_generality(hc, bh, d2)
        plot_history_activity_generality(bh, d2)

    control = None
    if RUN_CONTROL_FAMILY:
        control = run_hardcore_control_family()
        plot_control_family(control)

    scan = None
    if RUN_PARAMETER_SCAN:
        scan = run_parameter_scan()
        plot_parameter_scan(scan)

    boundary = None
    if RUN_BOUNDARY_DT_REFINEMENT:
        boundary = run_boundary_dt_refinement()
        plot_boundary_dt_refinement(boundary)

    local_defect = None
    if RUN_LOCAL_DEFECT_RATE:
        local_defect = run_local_defect_rate_analysis()
        plot_local_defect_rate(local_defect)
        plot_local_defect_absolute_scaling(local_defect)

    stats = None
    if RUN_STATISTICS_LIMIT:
        stats = statistics_limit_data()
        plot_statistics_limit(stats)

    floquet = None
    if RUN_FLOQUET:
        def build_floquet():
            N = 12 if not QUICK_TEST else 8
            Q = 3 if not QUICK_TEST else 2
            periods = 30 if not QUICK_TEST else 8
            return analyze_floquet_class(
                N=N,
                Q=Q,
                Kcells=4,
                periods=periods,
                theta_even=0.63,
                theta_odd=0.83,
                phi=0.77,
            )

        floquet = cached("floquet_generality", build_floquet)
        plot_floquet(floquet)

    save_summary(
        hc=hc,
        bh=bh,
        d2=d2,
        control=control,
        scan=scan,
        floquet=floquet,
        boundary=boundary,
        local_defect=local_defect,
    )

    print("\nAll requested generality calculations are configured.")
    print(f"Figures: {FIG_DIR}")
    print(f"Data:    {DATA_DIR}")
    print(f"Cache:   {CACHE_DIR}")


if __name__ == "__main__":
    main()